In [2]:
import numpy as np

In [3]:
from sklearn import datasets

In [4]:
import pandas as pd

In [19]:
data=np.genfromtxt("0000000000002419_training_ccpp_x_y_train.csv",delimiter=",")
x=data[:,0:4]
y=data[:,4]

data

array([[   8.58,   38.38, 1021.03,   84.37,  482.26],
       [  21.79,   58.2 , 1017.21,   66.74,  446.94],
       [  16.64,   48.92, 1011.55,   78.76,  452.56],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74,  437.65],
       [  16.37,   54.3 , 1017.94,   63.63,  459.97],
       [  30.11,   62.04, 1010.69,   47.96,  444.42]])

In [20]:
data=np.delete(data,4,1)
df=pd.DataFrame(x)
df["4"]=df[0]**2
df["5"]=df[1]**2
df["6"]=df[3]**2
print(df.head())
print(df.values)
x2=df.values

       0      1        2      3         4          5          6
0   8.58  38.38  1021.03  84.37   73.6164  1473.0244  7118.2969
1  21.79  58.20  1017.21  66.74  474.8041  3387.2400  4454.2276
2  16.64  48.92  1011.55  78.76  276.8896  2393.1664  6203.1376
3  31.38  71.32  1009.17  60.42  984.7044  5086.5424  3650.5764
4   9.20  40.03  1017.05  92.46   84.6400  1602.4009  8548.8516
[[   8.58     38.38   1021.03   ...   73.6164 1473.0244 7118.2969]
 [  21.79     58.2    1017.21   ...  474.8041 3387.24   4454.2276]
 [  16.64     48.92   1011.55   ...  276.8896 2393.1664 6203.1376]
 ...
 [  29.8      69.34   1009.36   ...  888.04   4808.0356 4191.2676]
 [  16.37     54.3    1017.94   ...  267.9769 2948.49   4048.7769]
 [  30.11     62.04   1010.69   ...  906.6121 3848.9616 2300.1616]]


In [21]:
from sklearn import preprocessing
scaler=preprocessing.MinMaxScaler()

scaler.fit(x2)
x2=scaler.transform(x2)
x2

array([[0.19935218, 0.2316726 , 0.69636229, ..., 0.05511626, 0.13811084,
        0.68932528],
       [0.58833922, 0.58434164, 0.60183123, ..., 0.36947327, 0.45667403,
        0.40527036],
       [0.43669022, 0.41921708, 0.46176689, ..., 0.21439422, 0.2912406 ,
        0.59174693],
       ...,
       [0.82420495, 0.78256228, 0.40757238, ..., 0.69327085, 0.69312241,
        0.3772324 ],
       [0.42873969, 0.51494662, 0.61989607, ..., 0.20741053, 0.38365739,
        0.3620394 ],
       [0.83333333, 0.65266904, 0.44048503, ..., 0.70782331, 0.5335136 ,
        0.17559426]])

In [22]:
df1=pd.DataFrame(x2)
df1["7"]=1
x2=df1.values
df1.head(5)

0         1         2         3         4         5         6  7
0  0.199352  0.231673  0.696362  0.788338  0.055116  0.138111  0.689325  1
1  0.588339  0.584342  0.601831  0.552011  0.369473  0.456674  0.405270  1
2  0.436690  0.419217  0.461767  0.713137  0.214394  0.291241  0.591747  1
3  0.870730  0.817794  0.402871  0.467292  0.769014  0.739471  0.319581  1
4  0.217609  0.261032  0.597872  0.896783  0.063754  0.159642  0.841857  1

In [66]:
iteration=300
#300 1018
#317 973
#325 955
#32675 953 611
#3275 953 609
#329 953 607
#3299 ... 605
#3315 ... 603
#332 ... 602
#3325 ... 601
#3320 ... 601
#33 959 605
#333 ... 601
#335 ... 598
#339 ... 598
#34 ... 603
#35 ... 5842
learning_rate=0.339

m=gradient_descent(x2,y,learning_rate,iteration)

print(m)

0 -> 168733.87693412372
1 -> 137741.62936814467
2 -> 112504.44552532825
3 -> 91949.3955935123
4 -> 75204.27016930384
5 -> 61559.87125455014
6 -> 50439.427754012075
7 -> 41373.779050251396
8 -> 33981.23115382936
9 -> 27951.1999723199
10 -> 23030.925504789808
11 -> 19014.677297162318
12 -> 15734.981715526017
13 -> 13055.490649760875
14 -> 10865.183266912285
15 -> 9073.65069581406
16 -> 7607.260694657151
17 -> 6406.037565015295
18 -> 5421.123546772483
19 -> 4612.713042531951
20 -> 3948.371393845164
21 -> 3401.666466306558
22 -> 2951.0547244680974
23 -> 2578.974379477659
24 -> 2271.107048801539
25 -> 2015.7765640920877
26 -> 1803.459412711948
27 -> 1626.3860539023378
28 -> 1478.2162174717096
29 -> 1353.7744378050404
30 -> 1248.8346341765669
31 -> 1159.9446295750838
32 -> 1084.283193681574
33 -> 1019.5435737050757
34 -> 963.8385983424589
35 -> 915.62335302018
36 -> 873.6321676947554
37 -> 836.8272634575952
38 -> 804.356896731471
39 -> 775.5212408807431
40 -> 749.7445716084105
41 -> 726.5525

In [71]:
x_test=np.genfromtxt("0000000000002419_test_ccpp_x_test.csv",delimiter=",")
df1=pd.DataFrame(x_test)
df1["4"]=df1[0]**2
df1["5"]=df1[1]**2
df1["6"]=df1[3]**2

x_test=df1.values
x_test=scaler.transform(x_test)
df1=pd.DataFrame(x_test)
df1["7"]=1
x_test=df1.values
df1.head(5)

0         1         2         3         4         5         6  7
0  0.298587  0.296619  0.610987  0.875737  0.109328  0.186954  0.811165  1
1  0.302120  0.229359  0.489483  0.752011  0.111587  0.136453  0.641351  1
2  0.739105  0.883096  0.315516  0.716086  0.564851  0.828832  0.595447  1
3  0.552709  0.252135  0.316506  0.489678  0.329302  0.153021  0.341396  1
4  0.440813  0.210676  0.472160  0.581501  0.218060  0.123269  0.437097  1

In [69]:
y_pred=predict(x_test,m)
y_pred

array([473.71592148, 467.37211769, 429.00603823, ..., 445.43172105,
       462.71837568, 462.15895212])

In [70]:
np.savetxt("power_y_pred2.csv",y_pred,fmt="%.5f",delimiter=",")

In [30]:
def predict(x_test,m):
    n=len(x)
    y_pred=np.zeros(2392)
    
    for i in range(2392):
        for j in range(8):
            y_pred[i]+=x_test[i][j]*m[j]
    return y_pred

In [29]:
def gradient_descent(x,y,learning_rate,iteration):
    m=np.zeros(8)
    for i in range(iteration):
        m=step_gradient(x,y,m,learning_rate)
        ans=cost(x,y,m)
        print(i,"->",ans)
    return m

In [24]:
def cost(x,y,m):
    n=len(x)
    
    cost1=0
    for i in range(n):
        mx=0
        for j in range(8):
            mx+=m[j]*x[i][j]
        cost1+=((y[i]-mx)**2)
        
    #print("here")
    return (1/n)*cost1

In [23]:
def step_gradient(x,y,m,learning_rate):
    m_slope=np.zeros(8)
    p=len(x)
    
    for i in range(p):
        sum=0
        for j in range(8):
            sum+=m[j]*x[i][j]
        sum=y[i]-sum
        
        for j in range(8):
            m_slope[j]+=(-2/p)*(x[i][j])*sum
            
    m=m-learning_rate*m_slope
    
    return m